# Generated by Django 3.0.7 on 2020-08-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_aboutmodels_hobbies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodels',
            name='hobbies',
        ),
        migrations.AddField(
            model_name='aboutmodels',
            name='hobbies',
            field=models.TextField(null=True),
        ),
    ]
