# Generated by Django 3.0.7 on 2020-08-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200810_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodels',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
