# Generated by Django 3.0.7 on 2020-08-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_aboutmodels_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.DateField(blank=True, null=True)),
                ('designation', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='aboutmodels',
            name='goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodels',
            name='projects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodels',
            name='values',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutmodels',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
