# Generated by Django 3.0.7 on 2020-08-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200813_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencemodels',
            name='duration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
