# Generated by Django 3.0.7 on 2020-08-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200813_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencemodels',
            name='duration',
        ),
        migrations.AddField(
            model_name='experiencemodels',
            name='duration_ending',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiencemodels',
            name='duration_starting',
            field=models.DateField(blank=True, null=True),
        ),
    ]
