# Generated by Django 3.0.7 on 2020-08-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20200813_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('college_name', models.CharField(blank=True, max_length=100, null=True)),
                ('course_starting', models.DateField(blank=True, null=True)),
                ('course_ending', models.DateField(blank=True, null=True)),
                ('percentage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('percentage', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='aboutmodels',
            name='hobbies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
